services:
  mongo:
    image: mongo:7
    container_name: shophub-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  postgres:
    image: postgres:15
    container_name: shophub-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: shophub
      POSTGRES_PASSWORD: shophub123
      POSTGRES_DB: ShopHubOrdering
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  mongo-data:
  postgres-data:
